### ISSUE TITLE
Playback control button icons still missing

### ISSUE THREAD

**Issue by chaosarium** [HugoFara/lwt#10] opened 2022-02-07 14:56 UTC
The app requests for `/src/css/images/jplayer.blue.monday.jpg` but the icon file is located in `/css/images/jplayer.blue.monday.jpg`

<img width="551" alt="Capture d’écran 2022-02-07 à 22 19 12" src="https://user-images.githubusercontent.com/38693485/152812362-5f298c00-1f3d-4d8e-ab60-f8341912863c.png">

**Comment by HugoFara** [comment] 2022-02-08 00:22
Hi! 

I never noticed this issue, since I spend more time developing than actually using the app, so when you say "*still* missing", I don't know when it started....

With version 2.2.0, I standardized theme import. Here, the problem is that  ``css/images/`` should go to ``src/css/images/``. As the images are required using CSS, it won't work with themes. 

**A quick-fix.** Just move ``css/images/`` to ``src/css/images/``. I could do it myself, but it means that you won't be able to customize all those images through themes.

**A clean fix.** More work needed, I need to find an *elegant* way to add themes, I find the current implementation of themes very awkward.

**Comment by chaosarium** [comment] 2022-02-08 02:08
Hi!

As I mentioned in #14, I like the idea of icon customization!

I have little experience with minifying from `src` so I was a bit confused by the two versions. I guess it has something to do with `Makefile`? 

Yeah, it would be great if icon customization could be more systematic!

**Comment by HugoFara** [comment] 2022-02-08 21:37
Hi,

I had little connection and a lot of time today, so I redacted a guide at [docs/contribute.md](https://github.com/HugoFara/lwt/blob/dev/docs/contribute.md) that explains everything.

If you installed LWT with Composer in dev mode, the Makefile adds useful commands to regenerate themes, just run ``make minify``. CSS and JS code are taken from ``src/css/`` or ``src/js/`` and minified into ``css/`` and ``js/`` respectively. You can also copy files manually but this is not recommended.

I never tested the Makefile on Windows (I am pretty confident it works on Mac), so feel free to open a new issue if it doesn't work!

**Comment by HugoFara** [comment] 2022-02-13 21:46
Bug fixed with [version 2.2.2](https://github.com/HugoFara/lwt/releases/tag/2.2.2).

I also added a section in [docs/contribute.md](https://github.com/HugoFara/lwt/blob/master/docs/contribute.md) that explains how to add your own images. The solution is straightforward for now: you can simply add the image anywhere, and the path is resolved with CSS minification, though it is better to add your custom images in your ``themes/yourtheme/`` folder. 

As images are not copied, this solution works, but a cleaner integration of themes will be needed some day!

**Closed by HugoFara** 2022-02-13 21:46 UTC
Labels: bug
