### ISSUE TITLE
hosted server - read page not showing anyhting

### ISSUE THREAD

**Issue by graciax452** [HugoFara/lwt#40] opened 2022-08-05 18:20 UTC
**Describe the bug**
The text does not show after i click read when lwt is installed on a hosted website server... (Original sourceforge installation works fine) 
I have reinstalled and reloaded at least  5 times no luck
The import had some errors but all text files seem to be there.

**To Reproduce**
Click read
Nothing shows

**Expected behavior**
click read
see text

**Screenshots**
![image](https://user-images.githubusercontent.com/25898582/183136979-a78c69fd-0944-42d0-8b35-771abf77e839.png)

![image](https://user-images.githubusercontent.com/25898582/183137056-5bbd9aee-a098-475e-93ad-f33ddc7ece2a.png)

**Desktop (please complete the following information):**
 - OS: windows 11,
 - Browser chrome and firefox

**Comment by HugoFara** [comment] 2022-08-11 09:35
Hi!

I will need some more information so that I can fix you problem, because I am unable to reproduce it. You mentioned "The import had some errors but all text files seem to be there.", no errors should happen, could you paste the errors?

**Comment by HugoFara** [comment] 2022-09-16 02:09
Hi! This issue have been fixed with the release [2.5.1](https://github.com/HugoFara/lwt/releases/tag/2.5.1). It still remains on terms import, I may take care of this part later.

**Closed by HugoFara** 2022-09-16 02:09 UTC
Labels: duplicate
